os: linux
env:
  - PARALLEL="--block 43K"

dist: trusty

cache:
  apt: true

addons:
  apt:
    update: true
    packages:
    - parallel
    - jq

script:
  - ./_sh/dupfolders.sh
  - ./_sh/dupfiles.sh
  - git remote add -f --tags upstream https://github.com/Arks-Layer/PSO2ENPatchCSV.git 2> /dev/null
  - ./_sh/UTF8.sh
  - ./_sh/EOL.sh
  - ./_sh/BOM.sh
  - ./_sh/CSV.sh
  - ./_sh/checkFiles.sh
  - ./_sh/quote.sh
  - ./_sh/dupCSV.sh
  - ./_sh/check.sh
  - ./_sh/command.sh
  - ./_sh/Fonts.sh
  - ./_sh/outputPO.sh > /dev/null

install:
  - true

language: python

virtualenv:
  system_site_packages: true
